### ISSUE TITLE
move the doc from containerd/contaienrd to contaienrd/containerd.io

### ISSUE THREAD

**Issue by DawnGuoDev** [containerd/containerd.io#97] opened 2021-08-10 08:56 UTC
Can I move the doc from containerd/contaienrd to contaienrd/containerd.io？I find some docs can be shared.

**Comment by AkihiroSuda** [comment] 2021-08-18 04:42
Yes, appreciated.

This was also discussed in https://github.com/containerd/containerd.io/issues/80 but got stall

**Comment by kzys** [comment] 2022-03-09 21:02
I actually want to have docs in containerd/containerd to keep them versioned, like https://www.envoyproxy.io/docs.

**Comment by AkihiroSuda** [comment] 2022-03-24 06:45
Closing as a duplicate of #80

**Closed by AkihiroSuda** 2022-03-24 06:45 UTC
Labels: duplicate
